### ISSUE TITLE
check howto make BlocklyDuino internationalizable

### ISSUE THREAD

**Issue by gasolin** [BlocklyDuino/BlocklyDuino#20]
Since latest merged blockly core has internationalization architecture, BlocklyDuino should align to blockly and provide strings in that way.

**Comment by SebCanet** [comment]
Thanks a lot !
A spanish teacher asked to translate my version, but he has to rewrite everything...
I hope with this new core it'll be more easy.
Thanks !

**Comment by SebCanet** [comment]
FINISHED ! I rewrite a totally new BlocklyDuino from Blockly's example 'code' with language menu.
Thanks a lot for your work taht helped me to start this work that is totally new from scratch. But as I use some of your code for Grove module, I mentioned your work. But I have to rewrite everything in Grove module to use 'relative' text from language file.

**Comment by gasolin** [comment]
great, would you like to point out your repo so somebody can redirect to your repo from here, or make a PR for BlocklyDuino?
